Algoritmo "ola_nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
   nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o seu nome completa: ")
   leia(nome)
   escreva("Ola ", nome, " seja bem-vindo")

Fimalgoritmo