Algoritmo "media_valores"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
   valor1,valor2, valor3, valor4, valor5, media : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Qual o 1º valor: ")
   leia(valor1)
   escreva("Qual o 2º valor: ")
   leia(valor2)
   escreva("Qual o 3º valor: ")
   leia(valor3)
   escreva("Qual o 4º valor: ")
   leia(valor4)
   escreva("Qual o 5º valor: ")
   leia(valor5)

   media <- (valor1+valor2+valor3+valor4+valor5)/5

   escreva("A media dos numeros é:", media)
   
   

Fimalgoritmo